### ISSUE TITLE
GitLab Fedora Migration

### ISSUE THREAD

**Issue by sethhillbrand** [KiCad/fedora-packaging#36]
Hi Fedora Wearers-

As part of the Great KiCad GitLab migration of 2019, I am testing the movement of open issues and PRs from GitHub to GitLab.

Here's what we know so far:

- Open Pull Requests will transfer to GitLab without moving the source of the PR.  That means pull requests will become GitLab Merge Requests that are referenced to the user's GitHub repository
- Open Issues will transfer to GitLab issues
- Closed/Resolved PRs and Issues will also transfer

In order to facilitate the transfer, it will be helpful if you can do two things:
- Open a GitLab account (these can use your GitHub OAuth)
- **Set your GitHub email to public**
- Let me know who the responsible parties are for the repository

The second point is critical because the migration script will only link users whose e-mail addresses match.  If the script can't see your GitHub e-mail address, the issue will be tied to the KiCad-Bot that performs the migration.

The timeline for the actual migration will be determined by the responsible parties from bullet 3 above but it would greatly assist my testing for bugs if you could do the first two steps above as soon as possible.

Thank you-
Seth

**Comment by nickoe** [comment]
@sethhillbrand I am responsible for this repo, but I think that @stevefalco has proven compentent enough that we can give him write access as well :) But I can also do that later on gitlab.

**Comment by sethhillbrand** [comment]
Excellent!  Thanks

**Comment by stevefalco** [comment]
I am @stevenfalco on gitlab and I've set up 2FA, so if you are willing to give me write access please go ahead when convenient.  I appreciate the opportunity to contribute more directly.

**Comment by sethhillbrand** [comment]
I'm going to resync using the KiCad Bot account this weekend and will update this thread when done.

At that point, I'll ask you to test the repo and, barring issues, we can archive this one

**Comment by nickoe** [comment]
I am not sure what you are syncing, but I moved the builders to gitlab, archiving repo.
